**By using list comprehension, please write a program to print the list after removing the value 24 in [12, 24, 35, 24, 88, 120, 155].**

In [1]:
print ([i for i in [12, 24, 35, 24, 88, 120, 155] if i != 24])

[12, 35, 88, 120, 155]


**With two given lists [1, 3, 6, 78, 35, 55] and [12, 24, 35, 24, 88, 120, 155], write a program to make a list whose elements are intersection of the above given lists.**

In [2]:
list1 = [1, 3, 6, 78, 35, 55]
list2 = [12, 24, 35, 24, 88, 120, 155]

a = set(list1)
b = set(list2)

i =  a.intersection(b)
print (list((i)))

[35]
